% measure cluster widths via polar transform
% measures centers from clusters generated by dbscan
% load bin file generated in clustering step - should include a cluster
% centers in CatInd_centers (2), and clustered molecules indexed by frame
% number
% radius_out saves measured radii as circle which encloses quantile% of
% molecules, e.g. circle containing 95% of molecules in cluster
% units are in px - multiply by px size to convert to nm

% initial category is 0 and 1

close all
clear
clc
quantile = 	1;% FWHM is 0.758
corr_ratio = 1; %  related to Out_Matrix(6,i)
Filter_n = 170;% The filtered out cluster, category is 3
pixelsize=114;

[r,filehead]=OpenMolList;
x=r.xc;
y=r.yc;
z=r.zc;

num_clusters = max(r.frame);

out_radius = zeros(numel(num_clusters),1);
out_avgZ = zeros(numel(num_clusters),1);
out_stdZ = zeros(numel(num_clusters),1);
out_num = zeros(numel(num_clusters),1);

out_sdx = zeros(numel(num_clusters),1);
out_sdy = zeros(numel(num_clusters),1);
out_avgx = zeros(numel(num_clusters),1);
out_avgy = zeros(numel(num_clusters),1);
out_frame = zeros(numel(num_clusters),1);

for i=1:num_clusters
    idx_use = find(r.frame==i);
    if isempty(idx_use)
        continue
    end
    
    x_use = x(idx_use);
    y_use = y(idx_use);
    z_use = z(idx_use);
    
    x_center = mean(x_use);
    y_center = mean(y_use);  
    x_shift = x_use-x_center;
    y_shift = y_use-y_center;
    [theta,radius] = cart2pol(x_shift,y_shift);
    radius_sort = sort(radius);
    radius_num = numel(radius_sort);
    out_radius(i) = radius_sort(round(radius_num*quantile))*corr_ratio;
    out_avgZ(i) = mean(z_use);
    out_stdZ(i) = std(z_use);
    out_num(i) = numel(idx_use);
    out_sdx(i) = std(x_use);
    out_sdy(i) = std(y_use);
    out_avgx(i) = mean(x_use);
    out_avgy(i) = mean(y_use);
    out_frame(i)= i;
end

Out_Matrix = [out_radius;out_avgx;out_sdx;out_avgy;out_sdy;out_avgZ;out_stdZ;out_num;out_frame];
Out_Matrix_Filter = zeros(8,0);
for i=2:num_clusters
    if Out_Matrix(8,i)>Filter_n
        Out_Matrix_Filter=[Out_Matrix_Filter,Out_Matrix(:,i)];
    else
        idx_use = find(r.frame==i);
        r.cat(idx_use)=3;
    end
end
[row,column]=size(Out_Matrix_Filter);
Add_on=zeros(1,column);
Add_on(1:1,1:column)=Filter_n;
Out_Matrix_Filter_Addon=[Add_on;Out_Matrix_Filter];
Out_Matrix_Filter_Addon=Out_Matrix_Filter_Addon.';

% 1. 获取文件夹路径
folder_path = fileparts(filehead);  % 'C:\Users\Admin\Results'

% 2. 获取原文件名（不含路径）
[~, base_name, ~] = fileparts(filehead);  % 'myData_experiment01'

% 3. 截掉最后 6 个字符（注意确保长度够）
if length(base_name) >= 10
    new_name = base_name(1:end-8);
else
    error('文件名不足10个字符，无法截断');
end

% 4. 拼接新的文件名（添加 .xlsx）
new_filename = [new_name, 'Filter.xlsx'];

% 5. 组合完整路径
outfile = fullfile(folder_path, new_filename);

% 6. 写入文件
writematrix(Out_Matrix_Filter, outfile);

% write bin file
new_filename2 = [new_name, '-F.bin'];
outfile2 = fullfile(folder_path, new_filename2);
WriteMolBinNXcYcZc(r,outfile2);

%correct for empty clusters
% out_idx = 1:numel(out_radius);
% idx_delete = find(out_radius==0);
% out_radius(idx_delete)=[];
% idx_corrected = out_idx;
% idx_corrected(idx_delete)=[];
% sdx(idx_delete)=[];
% sdy(idx_delete)=[];
% out_stdZ(idx_delete)=[];
% out_avgZ(idx_delete)=[];
% out_num(idx_delete)=[];

% smallROI_idx = find(out_radius<100);
% smallROI_idx_frame = idx_corrected(smallROI_idx);

